version: '3'
services:
  monitor-admin:
    image: cike/admin:latest
    container_name: fastdata-monitor-admin
    restart: always
    networks:
      - fastdata-net
    ports:
      - 8022:8022
    env_file: .env
    environment:
      TZ: Asia/Shanghai
  sentinel-dashboard:
    image: cike/sentinel-dashboard-docker:latest
    container_name: fastdata-sentinel-dashboard
    restart: always
    networks:
      - fastdata-net
    ports:
      - 8021:8021
    env_file: .env