version: '3.5'
services:
  nacos:
    image: nacos/nacos-server:1.1.3
    container_name: fastdata-nacos-standalone
    networks:
      - fastdata-net
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
    volumes:
      - ../data/nacos-server/logs/:/home/nacos/logs
    ports:
      - "8848:8848"
  prometheus:
    container_name: fastdata-prometheus
    image: prom/prometheus:latest
    networks:
      - fastdata-net
    volumes:
      - ./nacos/prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - nacos
    restart: on-failure

networks:
  fastdata-net:
    name: fastdata-net
    external: false