version: '3'
services:
  konga:
    image: pantsel/konga
    container_name: fastdata-konga
    depends_on:
      - kong
    networks:
      - fastdata-net
    env_file: .env
    ports:
      - 1337:1337/tcp

  kong:
    image: kong:latest
    container_name: fastdata-kong
    env_file: .env
    volumes:
      - ../data/kong:/usr/local/kong
    networks:
      - fastdata-net
    ports:
      - 18000:8000/tcp
      - 18443:8443/tcp
      - 18001:8001/tcp
      - 8444:8444/tcp
    depends_on:
      - postgres